# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

#variables:
#  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: ech Building!
- stage: RaviBuild
  jobs:
  - job: sampleapplbuild
    steps:
    - script: dotnet build --configuration Release
      displayName: 'dotnet build Release'

 